### ISSUE TITLE
Emacs 26 `xref` window management broke code1

### ISSUE THREAD

**Issue by wyuenho** [bmag/emacs-purpose#127] opened 2018-05-30 18:40 UTC
![screen capture](http://g.recordit.co/E92iWUGIkn.gif)

## Steps to reproduce
1. Install Emacs 26.1 (I've tested on the NS and the [Mituharu Mac port](https://github.com/railwaycat/homebrew-emacsmacport))
2. Call `(purpose-x-code1-setup)` in `.emacs`
3. Visit an ELISP file that has a symbol that will pop up an xref buffer for selection after `(xref-find-definitions)` (I visited `company.el`)
4. Adjust the edit window's width to something "small enough" (the screen cap edit window has a 93 (window-total-width)
4. Move point to the symbol (I moved to `company-backends`)
5. Press `M-.`
6. The window showing the `xref` buffer is covered with an extra `dired` buffer
7. Press `q` exits the dired buffer
8. Press `q` again to exit the `xref` buffer
9. Now we are back to the `dired` buffer we just quit and buried.
10. Press `q` twice to exit the dired buffer
11. Now there are 2 windows showing the file we visited.

## Expected behavior
The extra dired window should never show up to begin with.

I've git-bisected this issue to be caused by [this commit](https://github.com/emacs-mirror/emacs/commit/2a973edeacefcabb9fd8024188b7e167f0f9a9b6) to Emacs 26, all subsequent commits shows the same behavior.

I'm not exactly sure what's going on here, does this have something to do with some weird interaction with #98 ?

P.S. I have `pop-up-frames` set to `nil`.

**Comment by bmag** [comment] 2018-05-30 20:14
Couldn't reproduce it locally with, but did encounter some weirdness when using code1 while `purpose-mode` is disabled (which I think is to be expected).

Your repro steps don't mention if `purpose-mode` is enabled or not. Does this bug happen with or without `purpsoe-mode`?

**Comment by wyuenho** [comment] 2018-05-30 21:49
I was able to reproduce this with `open -a emacs --args -Q` and just `window-purpose` and `company` installed. I then `M-x purpose-mode` and followed up with `M-x company-mode` to warn up xref, and then tried `M-.` on one of the backend symbols on `company-backends` again.

**Comment by bmag** [comment] 2018-05-30 21:55
I think I found the bug, will fix tomorrow or the day after.

**Comment by bmag** [comment] 2018-05-31 17:49
Should be fixed by https://github.com/bmag/emacs-purpose/commit/a393b85d5a31f2a4a5fa5a720d412d910b4f5c59

**Comment by wyuenho** [comment] 2018-05-31 18:42
This fix made things much worst. Now a dired buffer will pop open and take over the edit buffer whenever I visit a file. The post-command-hook that updates the dired buffer also put it onto the edit buffer after every command

**Comment by bmag** [comment] 2018-05-31 19:07
Reverted for now.

**Closed** 2018-05-31 20:36 UTC
Labels: bug

**Comment by bmag** [comment] 2018-05-31 20:38
Ah, ok. Merged the fix, thanks.
